//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaInfo", Namespace="http://schemas.datacontract.org/2004/07/BTS.SICEP.Biometria.Entidades")]
    [System.SerializableAttribute()]
    public partial class PersonaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdentificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short anoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ceresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long folioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short municipioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Identificado {
            get {
                return this.IdentificadoField;
            }
            set {
                if ((this.IdentificadoField.Equals(value) != true)) {
                    this.IdentificadoField = value;
                    this.RaisePropertyChanged("Identificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ano {
            get {
                return this.anoField;
            }
            set {
                if ((this.anoField.Equals(value) != true)) {
                    this.anoField = value;
                    this.RaisePropertyChanged("ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cereso {
            get {
                return this.ceresoField;
            }
            set {
                if ((object.ReferenceEquals(this.ceresoField, value) != true)) {
                    this.ceresoField = value;
                    this.RaisePropertyChanged("cereso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long folio {
            get {
                return this.folioField;
            }
            set {
                if ((this.folioField.Equals(value) != true)) {
                    this.folioField = value;
                    this.RaisePropertyChanged("folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((this.municipioField.Equals(value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiometriaBusquedaServicio.IBiometriaServicio")]
    public interface IBiometriaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarHuella", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarHuellaResponse")]
        BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarHuella(string imagenBase64, int idBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarHuella", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarHuellaResponse")]
        System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarHuellaAsync(string imagenBase64, int idBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarFacial", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarFacialResponse")]
        BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarFacial(string imagenBase64, int idBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarFacial", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarFacialResponse")]
        System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarFacialAsync(string imagenBase64, int idBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarIris", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarIrisResponse")]
        BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarIris(string imagenBase64, int idBusqueda, short ojo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiometriaServicio/BuscarIris", ReplyAction="http://tempuri.org/IBiometriaServicio/BuscarIrisResponse")]
        System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarIrisAsync(string imagenBase64, int idBusqueda, short ojo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiometriaServicioChannel : BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.IBiometriaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiometriaServicioClient : System.ServiceModel.ClientBase<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.IBiometriaServicio>, BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.IBiometriaServicio {
        
        public BiometriaServicioClient() {
        }
        
        public BiometriaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiometriaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiometriaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiometriaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarHuella(string imagenBase64, int idBusqueda) {
            return base.Channel.BuscarHuella(imagenBase64, idBusqueda);
        }
        
        public System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarHuellaAsync(string imagenBase64, int idBusqueda) {
            return base.Channel.BuscarHuellaAsync(imagenBase64, idBusqueda);
        }
        
        public BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarFacial(string imagenBase64, int idBusqueda) {
            return base.Channel.BuscarFacial(imagenBase64, idBusqueda);
        }
        
        public System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarFacialAsync(string imagenBase64, int idBusqueda) {
            return base.Channel.BuscarFacialAsync(imagenBase64, idBusqueda);
        }
        
        public BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo BuscarIris(string imagenBase64, int idBusqueda, short ojo) {
            return base.Channel.BuscarIris(imagenBase64, idBusqueda, ojo);
        }
        
        public System.Threading.Tasks.Task<BTS.SiCEP.Biometria.Huellas.BiometriaBusquedaServicio.PersonaInfo> BuscarIrisAsync(string imagenBase64, int idBusqueda, short ojo) {
            return base.Channel.BuscarIrisAsync(imagenBase64, idBusqueda, ojo);
        }
    }
}
